version: '3.7'
services:

  database:
    image: redis:5.0.5
    ports:
      - 6379:6379
    networks:
      - like-it-network

  like-it:
    image: borodust/like-it:latest
    environment:
      - LIKEIT_REDIS_HOST=database
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - like-it-network

networks:
  like-it-network:
