version: '3.7'
services:
  like-it:
    image: borodust/like-it:latest
    environment:
      - LIKEIT_PROFILES=cluster
      - LIKEIT_REDIS_PASSWORD=${LIKEIT_REDIS_PASSWORD}
      - LIKEIT_REDIS_CLUSTER_NODES=${LIKEIT_REDIS_CLUSTER_NODES}
    ports:
      - 80:8080
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 15s
        window: 60s